FROM ruby:3.0.2-alpine

RUN apk update && apk upgrade && \
    apk add --update nodejs yarn git build-base libxml2 libxml2-dev libxml2-utils libxslt-dev tzdata imagemagick && \
    apk add libc6-compat sassc libsass && \
    apk add postgresql-dev postgresql-client && \
    apk add tesseract-ocr  tesseract-ocr-dev tesseract-ocr-data-deu leptonica leptonica-dev && \
    rm -rf /var/cache/apk/*

ENV HOME /app
ENV RAILS_ENV production
ENV RAILS_SERVE_STATIC_FILES true
ENV SECRET_KEY_BASE abcdefgh12345678

WORKDIR $HOME

# Install gems
ADD .ruby-version $HOME/
ADD Gemfile* $HOME/
RUN gem update bundler
# speed up install of nokogiri gem
RUN bundle config --local build.nokogiri --use-system-libraries
RUN bundle config set without 'development test'
RUN bundle install 

# Add the app code
COPY . $HOME

RUN bundle exec rake assets:precompile
