version: '3'
services:
  db:
    image: postgres:10.3-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  web:
    image: registry.gitlab.com/doerfli/reeper/prod:master
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
        RAILS_LOG_TO_STDOUT: "true"
