default: &default
  auth0_domain: <%= ENV.fetch("AUTH0_DOMAIN", 'domain') %>
  auth0_client_id: <%= ENV.fetch("AUTH0_CLIENT_ID", 'id') %>
  auth0_client_secret: <%= ENV.fetch("AUTH0_CLIENT_SECRET", 'secret') %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
