name: Ruby

on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.8'
        bundler-cache: true
    # - name: Run tests
    #   run: bundle exec rake

  brakeman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.8'
        bundler-cache: true
    - name: Run Brakeman SAST scanner
      run: bundle exec brakeman --no-pager -w2 --exit-on-warn

  # bundler-audit:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v6
  #   - uses: ruby/setup-ruby@v1
  #     with:
  #       ruby-version: '3.4.8'
  #       bundler-cache: true
  #   - name: Run bundler-audit
  #     run: bundle exec bundler-audit check --update

  # yarn-audit:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v6
  #   - uses: actions/setup-node@v4
  #     with:
  #       node-version: '24'
  #       cache: 'yarn'
  #   - run: yarn install --frozen-lockfile
  #   - name: Run yarn audit
  #     run: yarn audit --level high
